version: '2'

services:
  marco:
    build: ./
    volumes:
      - ./:/marco
    links:
      - rabbitmq
      - redis
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis
    ports:
      - 6379:6379