---
token: dc06516b8bc36a30770f6a394d8fd75ec5e93064022f5607a132081a4cc52c62
ssh_key_ids:           # DigitalOcean ID for your SSH Key
  - 3595653
userdata_master: master-data.erb
userdata_worker: worker-data.erb

inventory_file: inventory.json

droplet_options:
  hostname_prefix: marco
  region: fra1
  size: 512mb
  image: debian-8-x64


droplets:
  region: fra1
  image: debian-8-x64
  master:
    size: 1gb
  worker:
    size: 512mb
  strong_worker:
    size: 2gb
  database:
    size: 1gb